# H2 In-Memory DB
spring.datasource.url=${DB_URL:jdbc:h2:mem:user_management}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}

# H2 console
spring.h2.console.enabled=${H2_CONSOLE_ENABLED:true}
spring.h2.console.path=${H2_CONSOLE_PATH:/h2-console}

# JPA settings
spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

# Set the root log level
logging.level.root=${LOG_LEVEL_ROOT:INFO}

# Set log level for package
logging.level.com.example.RestApi.service=${LOG_LEVEL_APP:DEBUG}

# Log to file
logging.file.name=${LOG_FILE_NAME:logs/app.log}
logging.file.path=${LOG_FILE_PATH:./logs}
